name: Build macOS DMG

on:
  workflow_dispatch:        # permite rodar manualmente
  push:
    tags:
      - 'v*'                # também roda quando você criar uma tag

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build macOS app
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
        run: npm run dist

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4   # <--- AQUI AGORA É V4
        with:
          name: SorryLove-macOS
          path: dist/*.dmg
